export const FIVETH_STEP_SUBMIT_FORM = 'FIVETH_STEP_SUBMIT_FORM';
export const FIVETH_STEP_SHOW_PROGRESSBAR = 'FIVETH_STEP_SHOW_PROGRESSBAR';
export const FIVETH_STEP_HIDE_PROGRESSBAR = 'FIVETH_STEP_HIDE_PROGRESSBAR';
export const FIVETH_STEP_NEXT_STEP = 'FIVETH_STEP_NEXT_STEP';
export const FIVETH_STEP_SHOW_MESSAGE = 'FIVETH_STEP_SHOW_MESSAGE';
