export const SECOND_STEP_CHANGE_RADIO = 'SECOND_STEP_CHANGE_RADIO';
export const SECOND_STEP_SHOW_PROGRESSBAR = 'SECOND_STEP_SHOW_PROGRESSBAR';
export const SECOND_STEP_HIDE_PROGRESSBAR = 'SECOND_STEP_HIDE_PROGRESSBAR';
export const SECOND_STEP_NEXT_STEP = 'SECOND_STEP_NEXT_STEP';
