export const FIRST_STEP_CHANGE_CHECKBOX = 'FIRST_STEP_CHANGE_CHECKBOX';
export const FIRST_STEP_SHOW_PROGRESSBAR = 'FIRST_STEP_SHOW_PROGRESSBAR';
export const FIRST_STEP_HIDE_PROGRESSBAR = 'FIRST_STEP_HIDE_PROGRESSBAR';
export const FIRST_STEP_NEXT_STEP = 'FIRST_STEP_NEXT_STEP';
