export const THIRD_STEP_CHECK_TEXT = 'THIRD_STEP_CHECK_TEXT';
export const THIRD_STEP_SHOW_ERROR = 'THIRD_STEP_SHOW_ERROR';
export const THIRD_STEP_NEXT_STEP = 'THIRD_STEP_NEXT_STEP';
export const THIRD_STEP_CHANGE_INPUT = 'THIRD_STEP_CHANGE_INPUT';
export const THIRD_STEP_SHOW_PROGRESSSBAR = 'THIRD_STEP_SHOW_PROGRESSSBAR';
export const THIRD_STEP_HIDE_PROGRESSSBAR = 'THIRD_STEP_HIDE_PROGRESSSBAR';

