export const FOURTH_STEP_CHANGE_SELECT = 'FOURTH_STEP_CHANGE_SELECT';
export const FOURTH_STEP_SHOW_PROGRESSBAR = 'FOURTH_STEP_SHOW_PROGRESSBAR';
export const FOURTH_STEP_HIDE_PROGRESSBAR = 'FOURTH_STEP_HIDE_PROGRESSBAR';
export const FOURTH_STEP_NEXT_STEP = 'FOURTH_STEP_NEXT_STEP';
